### ISSUE TITLE
Questions: Jellyfin / Outputs / Python Structure

### ISSUE THREAD

**Issue by Erotemic** [tim000x3/CommercialBreaker#2]
Hi there,

I've been looking around for software to help create a self-hosted stream for personal use with custom content and commercials, and it looks like this it lays a lot of the groundwork.

I have a few questions:

* I see that you have some amount of Plex integration. I'm wondering if you would be interested in adding similar functionality for Jellyfin to enable a fully FOSS toolset.

* It looks like you have tools that scans media for good places to insert commercial breaks (hard problem; very interested in seeing how you solved it), is the output a set of movie files broken down into segments? I.e. does it create an extra copy of the data on disk? Or is there some lightweight sidecar format that just indicates the path to the video content and timestamps for where commercials should be inserted?

* Do you have collaberators on this project? What are you long-term plans for maintability? If you are interested, I'm a highly experienced Python programmer, and I could help organize this project with best-practices (e.g. package structure and entrypoints / requirements with minimum versions / robust pathing for ffmpeg / Automated Tests via Github Actions CI / cross-platform support).

**Comment by tim000x3** [comment]
I'd love some help we are not experienced developers as it says in the readme. I'd love to talk more about this I see you made some pull requests but this is actually not the most up to date version of the code. I will send you a pm with my contact details and we can talk wherever about this.

To answer a few questions off the bat. Would love to make it work with jellyfin I don't use it so I'm not as familiar. Finding places to put commercial breaks it what took half the time and we know how to make it much better but don't know "how". Yes currently it makes and extra copy but you can turn on destructive mode to delete the original if you want. We have an idea one how to make this unnecessary but we need to modify another project to do it and it's a bit over our heads.

Yes there are 2 people working on this project as a full time "hobby". We want to have a lot of goals for this project and would love some help. We are planning on making this work for any set of shows and commercials. The example we always talk about is if you swap the word Toonami for Disney it should still work since the bumps are similarly laid out.

**Comment by tim000x3** [comment]
I found your email in your bio and just sent you an email.
