### ISSUE TITLE
Episode naming convention

### ISSUE THREAD

**Issue by thebeanbag** [tim000x3/CommercialBreaker#8]
I might have missed it when I read through the README but it might be helpful to include what the naming convention should be for episode file names. ToonamiChecker wasn't recognizing any of the anime in my library because I had all my episodes titled like this: "Cowboy Bebop - 01x01". I had to do some print line debugging to figure out that the regular expression is looking for this naming convention "Cowboy Bebop - S01E01" .

Cheers!

**Comment by tim000x3** [comment]
Yes, there is also a naming convention for the bumps. Toonami [toonami version eg 2, 3 or blank for og] [placement 1 eg now] [show 1 eg inuyasha] [placement 2 eg to ads, back, next, or next from] [show name 2 eg bleach] [placement 3 eg later] [show name 3 eg one peice] [ad version if multiple versions is the same set eg 4] [color as some toonami bumps have color variations eg blue]

Eg

Toonami 3 Now Bleach Next Inuyasha Later Naruto 2 Blue

Toonami Bleach To Ads

There is also a thing for

Toonami Clydes 
Toonami Robots

For generic bumps

I need to update this and will soo n

Also, the name of the show can have another - and the episode name, I think, after what you said. 

Also, I think there can be underscores because we found some online did, so we just compensate if there is.

Sorry for the delay on this. I will do this as soon as I can very busy week. 

Also disclaimer I am typing this on my phone, and I'm only 90% sure this is correct, so I will be 100% before I update, but just a heads up.

**Comment by thebeanbag** [comment]
Thanks for the response. Is "Toonami 3 Now Bleach Next Inuyasha Later Naruto 2 Blue" considered a multibump? I have been having issues with the multibumps table being empty in the DB.

**Comment by tim000x3** [comment]
Yes a multi bump is anybump that contains more than 1 show. 

Toonami Bleach To Ads = a bump Toonami Bleach Next from Naruto = multibump 
Toonam now Bleach Next Naruto  later inuyasha = multibump

**Comment by tim000x3** [comment]
added better explanation to readme
